//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hms.Web.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Comment
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public System.DateTime Created { get; set; }
        public string Contents { get; set; }
        public int State { get; set; }
        public string IP { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
