//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hms.Web.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Elements
    {
        public int ID { get; set; }
        public int PageId { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string HTML { get; set; }
        public string Src { get; set; }
        public string Url { get; set; }
        public int SEQ { get; set; }
        public bool Enable { get; set; }
    }
}
