//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hms.Web.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pages
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string PageTitle { get; set; }
        public int SEQ { get; set; }
        public string SeoTitle { get; set; }
        public string SeoKeyWords { get; set; }
        public string SeoDescriptions { get; set; }
        public string Version { get; set; }
    }
}
