//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hms.Web.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Product
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public decimal Price { get; set; }
        public string Cover { get; set; }
        public string Tags { get; set; }
        public string Author { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public int Visitors { get; set; }
        public int Reading { get; set; }
        public string Contents { get; set; }
        public int State { get; set; }
    }
}
